language: csharp
solution: GlobalNameSorter.sln
dotnet: 2.1.300
mono: none
sudo: required

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      name: "Build"
      script: ./Scripts/build.sh
    - stage: test
      name: "Test"
      script: ./Scripts/test.sh
    - stage: deploy
      name: "Deploy"
      script: ./Scripts/deploy.sh



  on:
    branch: develop
