language: csharp
solution: GlobalNameSorter.sln
dotnet: 2.1.300
mono: none
sudo: required
script:
  - sudo apt-get install -y libcurl3
  - dotnet test --no-build --no-restore NameSorter.Tests/NameSorter.Tests.csproj

