language: csharp
solution: GlobalNameSorter.sln
dotnet: 2.1.300
mono: none
sudo: required

stages:
  - build
  - test
  - deploy


jobs:
  include:
    - stage build
    - stage test
    - stage deploy

build:
  provider: script
  script:
    - dotnet restore
    - dotnet pack -c Release

test:
  provider: script
  script:
    - cd NameSorter.Tests
    - dotnet test
    - cd ..

deploy:
  provider: script
  script:
    - dotnet pack -c Release
    - dotnet nuget push --source https://www.nuget.org --api-key $NUGET_API_KEY Service/bin/Release/*
  on:
    branch: develop
